<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Testcontainers.LocalStack" />
    <PackageReference Include="Testcontainers.Minio" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LocIntel.Api\LocIntel.Api.csproj" />
    <ProjectReference Include="..\..\src\Integrations\LocIntel.Integrations.AmazonS3\LocIntel.Integrations.AmazonS3.csproj" />
    <ProjectReference Include="..\..\src\Integrations\LocIntel.Integrations.AzureBlob\LocIntel.Integrations.AzureBlob.csproj" />
    <ProjectReference Include="..\..\src\Integrations\LocIntel.Integrations.Stripe\LocIntel.Integrations.Stripe.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Incidents\LocIntel.Modules.Incidents.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Entities\LocIntel.Modules.Entities.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Cases\LocIntel.Modules.Cases.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Marketplace\LocIntel.Modules.Marketplace.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Alerts\LocIntel.Modules.Alerts.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Network\LocIntel.Modules.Network.csproj" />
    <ProjectReference Include="..\..\src\Modules\LocIntel.Modules.Patrols\LocIntel.Modules.Patrols.csproj" />
  </ItemGroup>
</Project>
