namespace LocIntel.Contracts;

/// <summary>Durable publication of trusted, internally generated bytes; tenant/region on envelope.</summary>
public sealed record PublishGeneratedFile(
    Guid Id,
    string Key,
    string Name,
    string ContentType,
    long Bytes,
    Guid CreatedBy,
    DateTimeOffset CreatedAt,
    Guid[] SiteIds,
    string Origin,
    Guid OriginId
);
