using LocIntel.Modules.Marketplace.Marketplace;

namespace LocIntel.Modules.Marketplace.Requests.Api;

public sealed record RequestDetail(
    Guid Id,
    Guid? VendorOrgId,
    string? VendorName,
    RequestMode Mode,
    string RequesterName,
    ServiceCategory Category,
    RequestUrgency Urgency,
    RequestStatus Status,
    Guid SiteId,
    string SiteName,
    string SiteTimeZone,
    double? SiteLatitude,
    double? SiteLongitude,
    string Title,
    string Details,
    Dictionary<string, string> Spec,
    DateTimeOffset StartsAt,
    DateTimeOffset? EndsAt,
    string? Rrule,
    decimal? BudgetAmount,
    string Currency,
    Guid? IncidentId,
    Guid? CaseId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? SubmittedAt,
    DateTimeOffset? ResponseDueAt,
    DateTimeOffset? EscalatedAt,
    int EscalationCount,
    DateTimeOffset? AcceptedAt,
    string? DeclineReason,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    string? CompletionSummary,
    DateTimeOffset? VerifiedAt,
    string? DisputeReason,
    DateTimeOffset? CancelledAt,
    string? CancelReason,
    bool CanManage,
    IReadOnlyList<RequestEventView> Events,
    IReadOnlyList<QuoteView> Quotes,
    IReadOnlyList<RecipientView> Recipients
);
