using System.Text;
using LocIntel.Platform.Entitlements;
using LocIntel.Platform.Kernel;

// ADR 16: capability and entitlement keys generate from the C# catalogs into
// TS unions - one source of truth, two languages, no drift. Run via
// `pnpm codegen:keys` (or dotnet run) after changing either catalog.

var output = new StringBuilder();
output.AppendLine("// GENERATED by LocIntel.Tools.CodegenKeys - do not edit.");
output.AppendLine("// Source: LocIntel.Platform Capabilities + EntitlementCatalog.");
output.AppendLine();

output.AppendLine("export const CAPABILITIES = [");
foreach (var capability in Capabilities.All)
    output.AppendLine($"  '{capability}',");
output.AppendLine("] as const;");
output.AppendLine();
output.AppendLine("export type Capability = (typeof CAPABILITIES)[number];");
output.AppendLine();

output.AppendLine("export const ENTITLEMENTS = {");
foreach (var (code, descriptor) in EntitlementCatalog.Definitions.OrderBy(d => d.Key))
    output.AppendLine(
        $"  '{code}': {{ shape: '{descriptor.Shape}', policy: '{descriptor.Policy}', defaultValue: '{descriptor.DefaultValue}' }},"
    );
output.AppendLine("} as const;");
output.AppendLine();
output.AppendLine("export type EntitlementCode = keyof typeof ENTITLEMENTS;");

var root = AppContext.BaseDirectory;
string? repoRoot = null;
for (var dir = new DirectoryInfo(root); dir is not null; dir = dir.Parent)
    if (File.Exists(Path.Combine(dir.FullName, "LocIntel.slnx")))
    {
        repoRoot = dir.FullName;
        break;
    }
if (repoRoot is null)
{
    Console.Error.WriteLine("could not locate repo root (LocIntel.slnx)");
    return 1;
}
var target = Path.Combine(repoRoot, "web", "packages", "api", "src", "keys.ts");
Directory.CreateDirectory(Path.GetDirectoryName(target)!);
File.WriteAllText(target, output.ToString());
Console.WriteLine($"wrote {target}");
return 0;
