<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Modules/LocIntel.Modules.Reporting/LocIntel.Modules.Reporting.csproj" />
    <Content Include="Assets/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
