// GENERATED by LocIntel.Tools.CodegenKeys - do not edit.
// Source: LocIntel.Platform Capabilities + EntitlementCatalog.

export const CAPABILITIES = [
  'public:read',
  'sites:read',
  'sites:manage',
  'hierarchy:manage',
  'files:read',
  'files:manage',
  'ingest:manage',
  'reports:generate',
  'checklists:manage',
  'checklists:complete',
  'overlays:read',
  'overlays:manage',
  'audit:read',
  'audit:manage',
  'entitlements:manage',
  'roles:manage',
  'org:manage',
  'platform:operate',
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const ENTITLEMENTS = {
  'audit.read_logging': { shape: 'Boolean', policy: 'Block', defaultValue: 'true' },
  'audit.retention_days': { shape: 'Tiered', policy: 'WarnOnly', defaultValue: '90' },
  'contact_links.enabled': { shape: 'Boolean', policy: 'Block', defaultValue: 'true' },
  'contact_links.monthly': { shape: 'Metered', policy: 'Grace', defaultValue: '1000' },
  'hierarchy.depth': { shape: 'Limit', policy: 'Block', defaultValue: '4' },
  'reports.enabled': { shape: 'Boolean', policy: 'Block', defaultValue: 'true' },
  'reports.monthly': { shape: 'Limit', policy: 'Block', defaultValue: '1000' },
  'sites.max': { shape: 'Limit', policy: 'Block', defaultValue: '100' },
  'sso.enabled': { shape: 'Boolean', policy: 'Block', defaultValue: 'false' },
} as const;

export type EntitlementCode = keyof typeof ENTITLEMENTS;
