<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\LocIntel.Contracts\LocIntel.Contracts.csproj" />
    <ProjectReference Include="..\..\LocIntel.Platform\LocIntel.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp-MigraDoc" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Http" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Rendering/Fonts/*.ttf" />
    <Content Include="Rendering/Fonts/LICENSE_*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
